#!/usr/bin/env zsh

# Personal aliases and functions.
# For a full list of active aliases, run `alias`.

# ===== Editor =====
if [[ -x /opt/homebrew/bin/vim ]]; then
  alias vim="/opt/homebrew/bin/vim"
fi
if (( $+commands[nvim] )); then
  alias v="nvim"
  alias vi="nvim"
fi
if (( $+commands[code-insiders] )); then
  alias code="code-insiders"
fi

# ===== Modern CLI replacements =====
if (( $+commands[eza] )); then
  alias ls="eza --icons --group-directories-first"
  alias ll="eza -la --icons --group-directories-first --git"
  alias la="eza -a --icons --group-directories-first"
  alias lt="eza --tree --level=2 --icons"
  alias lt3="eza --tree --level=3 --icons"
fi
if (( $+commands[bat] )); then
  alias cat="bat --paging=never"
  alias catp="bat"  # with pager
fi
if (( $+commands[rg] )); then
  alias grep="rg"
fi
if (( $+commands[fd] )); then
  alias find="fd"
fi
if (( $+commands[dust] )); then
  alias du="dust"
fi
if (( $+commands[duf] )); then
  alias df="duf"
fi
if (( $+commands[procs] )); then
  alias ps="procs"
fi
if (( $+commands[btop] )); then
  alias top="btop"
fi
if (( $+commands[xh] )); then
  alias http="xh"
fi
if (( $+commands[tldr] )); then
  alias man="tldr"  # quick reference; use \man for full manual
fi

# ===== Navigation =====
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# ===== Safety =====
#alias rm="trash"
alias cp="cp -i"
alias mv="mv -i"
alias mkdir="mkdir -pv"

# ===== Utilities =====
alias weather="curl wttr.in"
alias myip="curl -s ifconfig.me"
alias ports="lsof -i -P -n | grep LISTEN"
alias path='echo $PATH | tr ":" "\n"'
alias reload="exec zsh"
alias latencies="curl http://cheat.sh/latencies"
alias cheat="curl cheat.sh/"

if [[ $OSTYPE == darwin* ]]; then
  alias localip="ipconfig getifaddr en0"
  alias flushdns="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"
  alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
  alias showfiles="defaults write com.apple.finder AppleShowAllFiles YES && killall Finder"
  alias hidefiles="defaults write com.apple.finder AppleShowAllFiles NO && killall Finder"
  alias afk="pmset displaysleepnow"
  alias emptytrash="trash -e"
fi

# ===== Development =====
alias todo='git grep -l TODO | xargs -n1 git blame -f -n -w | grep "$(git config user.name)" | grep TODO | sd ".\{9\}" "" | sd "\(.*\)[[:space:]]*" ""'
alias serve="python3 -m http.server"
if (( $+commands[jless] )); then
  alias json="jless"
fi
if (( $+commands[broot] )); then
  alias br="broot"
fi

# ===== FZF powered =====
if (( $+commands[fzf] && $+commands[bat] )); then
  alias preview="fzf --preview 'bat --color=always {}'"
fi
if (( $+commands[fzf] && $+commands[nvim] && $+commands[bat] )); then
  alias vf='nvim $(fzf --preview "bat --color=always {}")'  # fuzzy open in nvim
fi

# ===== Functions =====
timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
}

# Quick directory creation and cd
mkcd() {
  mkdir -p "$1" && cd "$1"
}

# Extract any archive
extract() {
  if [ -f "$1" ]; then
    case "$1" in
      *.tar.bz2) tar xjf "$1" ;;
      *.tar.gz)  tar xzf "$1" ;;
      *.tar.xz)  tar xJf "$1" ;;
      *.bz2)     bunzip2 "$1" ;;
      *.gz)      gunzip "$1" ;;
      *.tar)     tar xf "$1" ;;
      *.tbz2)    tar xjf "$1" ;;
      *.tgz)     tar xzf "$1" ;;
      *.zip)     unzip "$1" ;;
      *.Z)       uncompress "$1" ;;
      *.7z)      7z x "$1" ;;
      *)         echo "'$1' cannot be extracted" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# Quickly search and replace in files
replace() {
  if [ $# -lt 3 ]; then
    echo "Usage: replace <find> <replace> <glob>"
    return 1
  fi
  fd -t f "$3" -x sd "$1" "$2" {}
}


if [[ $OSTYPE == darwin* ]]; then
  # Monitor PTY usage (useful when running out of PTYs with Ghostty + Copilot CLI)
  pty() {
    local used=$(ls /dev/ttys* 2>/dev/null | wc -l | tr -d ' ')
    local max=$(sysctl -n kern.tty.ptmx_max)
    echo "${used} / ${max} PTYs in use"
  }

  pty-watch() {
    watch -n "${1:-5}" 'echo "$(ls /dev/ttys* | wc -l | tr -d " ") / $(sysctl -n kern.tty.ptmx_max) PTYs in use"'
  }
fi
