#!/usr/bin/env zsh

. "$HOME/.cargo/env"

export GPG_TTY=$(tty)
export GOPROXY=https://goproxy.githubapp.com/mod,https://proxy.golang.org/,direct
export GOPRIVATE=
export GONOPROXY=
export GONOSUMDB='github.com/github/*'
export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
export PATH="$PATH:/Users/mrecachinas/.dotnet/tools"
export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
export PATH="/opt/homebrew/opt/mysql@8.0/bin:$PATH"
export PATH="$PATH:/Users/mrecachinas/.local/bin"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export GITHUB_USERNAME=mrecachinas
