#!/usr/bin/env zsh

# Uncomment below to begin profiling
# zmodload zsh/zprof

# ===== Oh-My-Zsh Configuration =====
export ZSH="$HOME/.oh-my-zsh"

# Disable theme - using Starship instead
ZSH_THEME=""

# Performance settings
zstyle ':omz:update' mode disabled
DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_AUTO_UPDATE="true"
ZSH_DISABLE_COMPFIX="true"
DISABLE_COMPFIX="true"

# Smarter completion initialization (once per day)
autoload -Uz compinit
if [ "$(date +'%j')" != "$(stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)" ]; then
    compinit
else
    compinit -C
fi

# Lazy load nvm
zstyle ':omz:plugins:nvm' lazy yes

# Minimal plugin set
plugins=(
    git
    nvm
    fzf
)

# Autosuggest settings
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE="20"
ZSH_AUTOSUGGEST_USE_ASYNC=1

source $ZSH/oh-my-zsh.sh

# ===== Lazy-load rbenv =====
rbenv() {
    unfunction rbenv
    eval "$(command rbenv init -)"
    rbenv "$@"
}
# Ensure ruby/gem commands also trigger rbenv init
ruby() { rbenv version >/dev/null; unfunction ruby; ruby "$@"; }
gem() { rbenv version >/dev/null; unfunction gem; gem "$@"; }

# ===== Tool Integrations =====
# Zoxide (smarter cd)
eval "$(zoxide init zsh)"

# Atuin (better shell history)
eval "$(atuin init zsh --disable-up-arrow)"

# Broot (tree navigation)
[ -f ~/.config/broot/launcher/bash/br ] && source ~/.config/broot/launcher/bash/br

# ===== Lazy Sources =====
[ -s ~/.bun/_bun ] && source ~/.bun/_bun
[ -f ~/.cargo/env ] && source ~/.cargo/env
[ -f ~/.config/op/plugins.sh ] && source ~/.config/op/plugins.sh

# ===== Personal Config =====
[ -f ~/.zsh_env ] && source ~/.zsh_env
[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases

# ===== Starship Prompt (must be last) =====
eval "$(starship init zsh)"

# Uncomment below to begin profiling
# zprof
source /Users/mrecachinas/.config/op/plugins.sh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
